### PR TITLE
fix: Add support for CVSS V4 metrics in NVD conversion

### LINKED ISSUE #4157: Support CVSS4 in NVD conversion

### PR DESCRIPTION
**Pull request by jess-lowe**
Closes #4157

### CODE REVIEW

File: vulnfeeds/cves/nvd2.go [hunk 1]
```diff
@@ -224,6 +224,15 @@ type CVSSV31 struct {
 	ImpactScore         *DefSubscore `json:"impactScore,omitempty"         mapstructure:"impactScore,omitempty"         yaml:"impactScore,omitempty"`
 }
 
+// CVSS V4.0 score. (hand-generated)
+type CVSSV40 struct {
```
Comment (michaelkedar) [inline vulnfeeds/cves/nvd2.go]: Aren't these CVSSVX structs all the same?
Should we just consolidate them?

File: vulnfeeds/cves/nvd2.go [hunk 2]
```diff
@@ -234,6 +243,9 @@ type CVEItemMetrics struct {
 
 	// CVSS V3.1 score.
 	CVSSMetricV31 []CVSSV31 `json:"cvssMetricV31,omitempty" mapstructure:"cvssMetricV31,omitempty" yaml:"cvssMetricV31,omitempty"`
+
+	// CVSS V4 score
+	CVSSMetricV4 []CVSSV40 `json:"cvssMetricV40,omitempty" mapstructure:"cvssMetricV31,omitempty" yaml:"cvssMetricV31,omitempty"`
```
Comment (another-rex) [inline vulnfeeds/cves/nvd2.go]: map structure and yaml?

File: vulnfeeds/cves/nvd2.go [hunk 3]
```diff
@@ -206,17 +206,8 @@ type CVSSV2 struct {
...
-	Type                string       `json:"type"                          mapstructure:"type"                          yaml:"type"`
-	CVSSData            CVSS         `json:"cvssData"                      mapstructure:"cvssData"                      yaml:"cvssData"`
-	ExploitabilityScore *DefSubscore `json:"exploitabilityScore,omitempty" mapstructure:"exploitabilityScore,omitempty" yaml:"exploitabilityScore,omitempty"`
-	ImpactScore         *DefSubscore `json:"impactScore,omitempty"         mapstructure:"impactScore,omitempty"         yaml:"impactScore,omitempty"`
-}
-
-// CVSS V3.1 score. (hand-generated)
-type CVSSV31 struct {
+// CVSS Score to encapsulate V3.0, V3.1, V4.0 structs
+type BaseCVSSNVD struct {
```
Comment (another-rex) [inline vulnfeeds/cves/nvd2.go:210]: If 3.0, 3.1, and 4.0 are the same fields, what's the difference between the versions? Or are we missing the fields that this actually affects?

Comment (jess-lowe) [reply vulnfeeds/cves/nvd2.go:210]: Basically, this is only here afaik, so we can prioritize which severity score we are getting. The actual field is just the vector string which is just a string so doesn't really type that well.

Comment (another-rex) [reply vulnfeeds/cves/nvd2.go:210]: Ah ok, we only care about Type and CVSSData.VectorString? If so, let's just comment out the other fields to avoid confusion.
